lib/blog_phoenix_web/router.ex
defmodule BlogPhoenixWeb.Router do
  use BlogPhoenixWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", BlogPhoenixWeb do
    pipe_through :browser

    # get "/", PageController, :index
    get "/", PostController, :index
    resources "/posts", PostController
    resources "/registrations", UserController, only: [:new, :create]
    
    get "/sign-in", SessionController, :new
    post "/sign-in", SessionController, :create
    delete "/sign-out", SessionController, :delete
  end

  # Other scopes may use custom stacks.
  # scope "/api", BlogPhoenixWeb do
  #   pipe_through :api
  # end
end

lib/blog_phoenix_web/views/layout_view.ex
defmodule BlogPhoenixWeb.LayoutView do
  use BlogPhoenixWeb, :view
end

lib/blog_phoenix_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Blog App</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation">
          <%= if signed_in?(@conn) do %>
            <%= link "Sign Out", to: Routes.session_path(@conn, :delete), method: :delete %>
          <% else %>
            <%= link "Sign In", to: Routes.session_path(@conn, :new) %>
            <%= link "Sign Up", to: Routes.user_path(@conn, :new) %>
          <% end %>
        </nav>
        <div class="cropped">
        <a href="/" class="phx-logo cropped1">
          <img src="<%= Routes.static_path(@conn, "/images/phoenix.png") %>" alt="Phoenix Framework Logo"/>
          <span>BlogApp</span>
        </a>
        </div>
      </section>
    </header>
    <main role="main" class="container">
      
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>